2025-03-28 15:01:23,818 - log_util.py[DEBUG]: Cloud-init v. 24.4-0ubuntu1~24.04.2 running 'init-local' at Fri, 28 Mar 2025 15:01:23 +0000. Up 43.02 seconds.
2025-03-28 15:01:23,818 - main.py[INFO]: PID [1] started cloud-init 'init-local'.
2025-03-28 15:01:23,818 - main.py[DEBUG]: No kernel command line url found.
2025-03-28 15:01:23,819 - main.py[DEBUG]: Closing stdin
2025-03-28 15:01:23,837 - util.py[DEBUG]: Writing to /var/log/cloud-init.log - ab: [640] 0 bytes
2025-03-28 15:01:23,839 - util.py[DEBUG]: Changing the ownership of /var/log/cloud-init.log to 102:4
2025-03-28 15:01:23,839 - util.py[DEBUG]: Writing to /var/lib/cloud/data/python-version - wb: [644] 4 bytes
2025-03-28 15:01:23,842 - util.py[DEBUG]: Attempting to remove /var/lib/cloud/instance/boot-finished
2025-03-28 15:01:23,843 - handlers.py[DEBUG]: start: init-local/check-cache: attempting to read from cache [check]
2025-03-28 15:01:23,843 - util.py[DEBUG]: Reading from /var/lib/cloud/instance/obj.pkl (quiet=False)
2025-03-28 15:01:23,845 - stages.py[DEBUG]: no cache found
2025-03-28 15:01:23,845 - handlers.py[DEBUG]: finish: init-local/check-cache: SUCCESS: no cache found
2025-03-28 15:01:23,860 - stages.py[DEBUG]: Using distro class <class 'cloudinit.distros.ubuntu.Distro'>
2025-03-28 15:01:23,863 - sources[DEBUG]: Looking for data source in: ['None'], via packages ['', 'cloudinit.sources'] that matches dependencies ['FILESYSTEM']
2025-03-28 15:01:23,883 - sources[DEBUG]: Searching for local data source in: []
2025-03-28 15:01:23,883 - util.py[DEBUG]: Reading from /var/lib/cloud/instance/obj.pkl (quiet=False)
2025-03-28 15:01:23,883 - util.py[DEBUG]: Attempting to remove /var/lib/cloud/instance
2025-03-28 15:01:23,883 - main.py[DEBUG]: No local datasource found
2025-03-28 15:01:23,886 - util.py[DEBUG]: Reading from /sys/class/net/ens33/address (quiet=False)
2025-03-28 15:01:23,887 - util.py[DEBUG]: Reading 18 bytes from /sys/class/net/ens33/address
2025-03-28 15:01:23,887 - util.py[DEBUG]: Reading from /sys/class/net/lo/address (quiet=False)
2025-03-28 15:01:23,887 - util.py[DEBUG]: Reading 18 bytes from /sys/class/net/lo/address
2025-03-28 15:01:23,888 - util.py[DEBUG]: Reading from /sys/class/net/ens33/address (quiet=False)
2025-03-28 15:01:23,888 - util.py[DEBUG]: Reading 18 bytes from /sys/class/net/ens33/address
2025-03-28 15:01:23,888 - util.py[DEBUG]: Reading from /sys/class/net/lo/address (quiet=False)
2025-03-28 15:01:23,888 - util.py[DEBUG]: Reading 18 bytes from /sys/class/net/lo/address
2025-03-28 15:01:23,889 - util.py[DEBUG]: Reading from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-network-config-v2.json (quiet=False)
2025-03-28 15:01:23,893 - util.py[DEBUG]: Reading 17906 bytes from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-network-config-v2.json
2025-03-28 15:01:23,893 - schema.py[DEBUG]: Validating network-config with netplan API
2025-03-28 15:01:23,899 - util.py[DEBUG]: Writing to /run/cloud-init/tmp/tmp0eyxp2t_/etc/netplan/network-config.yaml - wb: [600] 86 bytes
2025-03-28 15:01:23,903 - performance.py[DEBUG]: Validating schema took 0.015 seconds
2025-03-28 15:01:23,904 - util.py[DEBUG]: Reading from /sys/class/net/ens33/addr_assign_type (quiet=False)
2025-03-28 15:01:23,904 - util.py[DEBUG]: Reading 2 bytes from /sys/class/net/ens33/addr_assign_type
2025-03-28 15:01:23,904 - util.py[DEBUG]: Reading from /sys/class/net/ens33/uevent (quiet=False)
2025-03-28 15:01:23,905 - util.py[DEBUG]: Reading 26 bytes from /sys/class/net/ens33/uevent
2025-03-28 15:01:23,905 - util.py[DEBUG]: Reading from /sys/class/net/ens33/address (quiet=False)
2025-03-28 15:01:23,906 - util.py[DEBUG]: Reading 18 bytes from /sys/class/net/ens33/address
2025-03-28 15:01:23,908 - net[DEBUG]: ovs-vsctl not in PATH; not detecting Open vSwitch interfaces
2025-03-28 15:01:23,908 - util.py[DEBUG]: Reading from /sys/class/net/ens33/device/device (quiet=False)
2025-03-28 15:01:23,909 - util.py[DEBUG]: Reading 7 bytes from /sys/class/net/ens33/device/device
2025-03-28 15:01:23,909 - util.py[DEBUG]: Reading from /sys/class/net/lo/addr_assign_type (quiet=False)
2025-03-28 15:01:23,909 - util.py[DEBUG]: Reading 2 bytes from /sys/class/net/lo/addr_assign_type
2025-03-28 15:01:23,910 - util.py[DEBUG]: Reading from /sys/class/net/lo/uevent (quiet=False)
2025-03-28 15:01:23,910 - util.py[DEBUG]: Reading 23 bytes from /sys/class/net/lo/uevent
2025-03-28 15:01:23,912 - util.py[DEBUG]: Reading from /sys/class/net/lo/address (quiet=False)
2025-03-28 15:01:23,913 - util.py[DEBUG]: Reading 18 bytes from /sys/class/net/lo/address
2025-03-28 15:01:23,913 - util.py[DEBUG]: Reading from /sys/class/net/lo/device/device (quiet=False)
2025-03-28 15:01:23,913 - util.py[DEBUG]: Reading from /sys/class/net/ens33/type (quiet=False)
2025-03-28 15:01:23,913 - util.py[DEBUG]: Reading 2 bytes from /sys/class/net/ens33/type
2025-03-28 15:01:23,913 - util.py[DEBUG]: Reading from /sys/class/net/lo/type (quiet=False)
2025-03-28 15:01:23,914 - util.py[DEBUG]: Reading 4 bytes from /sys/class/net/lo/type
2025-03-28 15:01:23,916 - networking.py[DEBUG]: net: all expected physical devices present
2025-03-28 15:01:23,916 - stages.py[DEBUG]: applying net config names for {'ethernets': {'ens33': {'dhcp4': True}}, 'version': 2}
2025-03-28 15:01:23,916 - net[DEBUG]: no interfaces to rename
2025-03-28 15:01:23,917 - stages.py[INFO]: Applying network configuration from system_cfg bringup=False: {'ethernets': {'ens33': {'dhcp4': True}}, 'version': 2}
2025-03-28 15:01:23,918 - util.py[DEBUG]: Writing to /run/cloud-init/sem/apply_network_config.once - wb: [644] 24 bytes
2025-03-28 15:01:23,950 - distros[DEBUG]: Selected renderer 'netplan' from priority list: ['netplan', 'eni', 'sysconfig']
2025-03-28 15:01:23,951 - network_state.py[DEBUG]: Passthrough netplan v2 config
2025-03-28 15:01:24,016 - netplan.py[DEBUG]: V2 to V2 passthrough
2025-03-28 15:01:24,021 - netplan.py[DEBUG]: Rendered netplan config using netplan python API
2025-03-28 15:01:24,022 - subp.py[DEBUG]: Running command ['netplan', 'generate'] with allowed return codes [0] (shell=False, capture=True)
2025-03-28 15:01:29,076 - performance.py[DEBUG]: Running ['netplan', 'generate'] took 5.053 seconds
2025-03-28 15:01:29,076 - subp.py[DEBUG]: Running command ['udevadm', 'test-builtin', 'net_setup_link', '/sys/class/net/ens33'] with allowed return codes [0] (shell=False, capture=True)
2025-03-28 15:01:29,091 - performance.py[DEBUG]: Running ['udevadm', 'test-builtin', 'net_setup_link', '/sys/class/net/ens33'] took 0.014 seconds
2025-03-28 15:01:29,091 - subp.py[DEBUG]: Running command ['udevadm', 'test-builtin', 'net_setup_link', '/sys/class/net/lo'] with allowed return codes [0] (shell=False, capture=True)
2025-03-28 15:01:29,107 - performance.py[DEBUG]: Running ['udevadm', 'test-builtin', 'net_setup_link', '/sys/class/net/lo'] took 0.016 seconds
2025-03-28 15:01:29,108 - distros[DEBUG]: Not bringing up newly configured network interfaces
2025-03-28 15:01:29,108 - main.py[DEBUG]: [local] Exiting without datasource
2025-03-28 15:01:29,108 - util.py[DEBUG]: Reading from /proc/uptime (quiet=False)
2025-03-28 15:01:29,109 - util.py[DEBUG]: Reading 12 bytes from /proc/uptime
2025-03-28 15:01:29,110 - atomic_helper.py[DEBUG]: Atomically writing to file /var/lib/cloud/data/status.json (via temporary file /var/lib/cloud/data/tmpzxb_0pln) - w: [644] 484 bytes/chars
2025-03-28 15:01:29,113 - performance.py[DEBUG]: cloud-init stage: 'init-local' took 5.496 seconds
2025-03-28 15:01:29,113 - handlers.py[DEBUG]: finish: init-local: SUCCESS: searching for local datasources
2025-03-28 15:01:49,868 - log_util.py[DEBUG]: Cloud-init v. 24.4-0ubuntu1~24.04.2 running 'init' at Fri, 28 Mar 2025 15:01:49 +0000. Up 69.10 seconds.
2025-03-28 15:01:49,868 - main.py[INFO]: PID [1] started cloud-init 'init'.
2025-03-28 15:01:49,869 - main.py[DEBUG]: No kernel command line url found.
2025-03-28 15:01:49,870 - main.py[DEBUG]: Closing stdin
2025-03-28 15:01:49,876 - util.py[DEBUG]: Writing to /var/log/cloud-init.log - ab: [640] 0 bytes
2025-03-28 15:01:49,878 - util.py[DEBUG]: Changing the ownership of /var/log/cloud-init.log to 102:4
2025-03-28 15:01:49,879 - util.py[DEBUG]: Reading from /var/lib/cloud/data/python-version (quiet=False)
2025-03-28 15:01:49,879 - util.py[DEBUG]: Reading 4 bytes from /var/lib/cloud/data/python-version
2025-03-28 15:01:49,879 - main.py[DEBUG]: Will wait for network connectivity before continuing
2025-03-28 15:01:49,883 - stages.py[DEBUG]: Using distro class <class 'cloudinit.distros.ubuntu.Distro'>
2025-03-28 15:01:49,885 - activators.py[DEBUG]: Using selected activator: <class 'cloudinit.net.activators.NetplanActivator'> from priority: ['netplan', 'eni', 'network-manager', 'networkd']
2025-03-28 15:01:49,885 - subp.py[DEBUG]: Running command ['systemctl', 'is-enabled', 'NetworkManager.service'] with allowed return codes [0] (shell=False, capture=True)
2025-03-28 15:01:49,979 - performance.py[DEBUG]: Running ['systemctl', 'is-enabled', 'NetworkManager.service'] took 0.093 seconds
2025-03-28 15:01:49,979 - activators.py[DEBUG]: NetworkManager is enabled, skipping networkd wait
2025-03-28 15:01:49,980 - subp.py[DEBUG]: Running command ['ip', '--json', 'addr'] with allowed return codes [0] (shell=False, capture=True)
2025-03-28 15:01:50,442 - performance.py[DEBUG]: Running ['ip', '--json', 'addr'] took 0.462 seconds
2025-03-28 15:01:50,445 - subp.py[DEBUG]: Running command ['ip', '-o', 'route', 'list'] with allowed return codes [0] (shell=False, capture=True)
2025-03-28 15:01:50,453 - subp.py[DEBUG]: Running command ['ip', '--oneline', '-6', 'route', 'list', 'table', 'all'] with allowed return codes [0, 1] (shell=False, capture=True)
2025-03-28 15:01:50,482 - performance.py[DEBUG]: Running ['ip', '--oneline', '-6', 'route', 'list', 'table', 'all'] took 0.028 seconds
2025-03-28 15:01:50,484 - handlers.py[DEBUG]: start: init-network/check-cache: attempting to read from cache [trust]
2025-03-28 15:01:50,486 - util.py[DEBUG]: Reading from /var/lib/cloud/instance/obj.pkl (quiet=False)
2025-03-28 15:01:50,486 - stages.py[DEBUG]: no cache found
2025-03-28 15:01:50,486 - handlers.py[DEBUG]: finish: init-network/check-cache: SUCCESS: no cache found
2025-03-28 15:01:50,491 - sources[DEBUG]: Looking for data source in: ['None'], via packages ['', 'cloudinit.sources'] that matches dependencies ['FILESYSTEM', 'NETWORK']
2025-03-28 15:01:50,495 - sources[DEBUG]: Searching for network data source in: ['DataSourceNone']
2025-03-28 15:01:50,495 - handlers.py[DEBUG]: start: init-network/search-None: searching for network data from DataSourceNone
2025-03-28 15:01:50,496 - sources[DEBUG]: Seeing if we can get any data from <class 'cloudinit.sources.DataSourceNone.DataSourceNone'>
2025-03-28 15:01:50,496 - sources[DEBUG]: Update datasource metadata and network config due to events: boot-new-instance
2025-03-28 15:01:50,498 - sources[DEBUG]: Datasource list set to use a single datasource DataSourceNone.
2025-03-28 15:01:50,499 - util.py[DEBUG]: Reading from /etc/hosts (quiet=False)
2025-03-28 15:01:50,499 - util.py[DEBUG]: Reading 221 bytes from /etc/hosts
2025-03-28 15:01:50,503 - util.py[DEBUG]: Writing to /run/cloud-init/cloud-id-none - wb: [644] 5 bytes
2025-03-28 15:01:50,504 - util.py[DEBUG]: Creating symbolic link from '/run/cloud-init/cloud-id' => '/run/cloud-init/cloud-id-none'
2025-03-28 15:01:50,506 - atomic_helper.py[DEBUG]: Atomically writing to file /run/cloud-init/instance-data-sensitive.json (via temporary file /run/cloud-init/tmpfupvdq_4) - w: [600] 9865 bytes/chars
2025-03-28 15:01:50,508 - atomic_helper.py[DEBUG]: Atomically writing to file /run/cloud-init/instance-data.json (via temporary file /run/cloud-init/tmpho70k1ch) - w: [644] 1496 bytes/chars
2025-03-28 15:01:50,508 - performance.py[DEBUG]: Getting metadata took 0.012 seconds
2025-03-28 15:01:50,509 - handlers.py[DEBUG]: finish: init-network/search-None: SUCCESS: found network data from DataSourceNone
2025-03-28 15:01:50,510 - util.py[DEBUG]: Attempting to remove /var/lib/cloud/instance
2025-03-28 15:01:50,510 - stages.py[INFO]: Loaded datasource DataSourceNone - DataSourceNone
2025-03-28 15:01:50,510 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg (quiet=False)
2025-03-28 15:01:50,511 - util.py[DEBUG]: Reading 3718 bytes from /etc/cloud/cloud.cfg
2025-03-28 15:01:50,511 - util.py[DEBUG]: Attempting to load yaml from string of length 3718 with allowed root types (<class 'dict'>,)
2025-03-28 15:01:50,540 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/curtin-preserve-sources.cfg (quiet=False)
2025-03-28 15:01:50,540 - util.py[DEBUG]: Reading 35 bytes from /etc/cloud/cloud.cfg.d/curtin-preserve-sources.cfg
2025-03-28 15:01:50,540 - util.py[DEBUG]: Attempting to load yaml from string of length 35 with allowed root types (<class 'dict'>,)
2025-03-28 15:01:50,541 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/99-installer.cfg (quiet=False)
2025-03-28 15:01:50,542 - util.py[DEBUG]: Reading 806 bytes from /etc/cloud/cloud.cfg.d/99-installer.cfg
2025-03-28 15:01:50,542 - util.py[DEBUG]: Attempting to load yaml from string of length 806 with allowed root types (<class 'dict'>,)
2025-03-28 15:01:50,546 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/90_dpkg.cfg (quiet=False)
2025-03-28 15:01:50,546 - util.py[DEBUG]: Reading 333 bytes from /etc/cloud/cloud.cfg.d/90_dpkg.cfg
2025-03-28 15:01:50,546 - util.py[DEBUG]: Attempting to load yaml from string of length 333 with allowed root types (<class 'dict'>,)
2025-03-28 15:01:50,551 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/90-installer-network.cfg (quiet=False)
2025-03-28 15:01:50,552 - util.py[DEBUG]: Reading 116 bytes from /etc/cloud/cloud.cfg.d/90-installer-network.cfg
2025-03-28 15:01:50,552 - util.py[DEBUG]: Attempting to load yaml from string of length 116 with allowed root types (<class 'dict'>,)
2025-03-28 15:01:50,554 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/20-disable-cc-dpkg-grub.cfg (quiet=False)
2025-03-28 15:01:50,554 - util.py[DEBUG]: Reading 28 bytes from /etc/cloud/cloud.cfg.d/20-disable-cc-dpkg-grub.cfg
2025-03-28 15:01:50,555 - util.py[DEBUG]: Attempting to load yaml from string of length 28 with allowed root types (<class 'dict'>,)
2025-03-28 15:01:50,556 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/05_logging.cfg (quiet=False)
2025-03-28 15:01:50,556 - util.py[DEBUG]: Reading 2071 bytes from /etc/cloud/cloud.cfg.d/05_logging.cfg
2025-03-28 15:01:50,556 - util.py[DEBUG]: Attempting to load yaml from string of length 2071 with allowed root types (<class 'dict'>,)
2025-03-28 15:01:50,563 - util.py[DEBUG]: Reading from /run/cloud-init/cloud.cfg (quiet=False)
2025-03-28 15:01:50,563 - util.py[DEBUG]: Attempting to load yaml from string of length 0 with allowed root types (<class 'dict'>,)
2025-03-28 15:01:50,564 - util.py[DEBUG]: loaded blob returned None, returning default.
2025-03-28 15:01:50,565 - util.py[DEBUG]: Attempting to remove /var/lib/cloud/instance
2025-03-28 15:01:50,565 - util.py[DEBUG]: Creating symbolic link from '/var/lib/cloud/instance' => '/var/lib/cloud/instances/iid-datasource-none'
2025-03-28 15:01:50,568 - util.py[DEBUG]: Reading from /var/lib/cloud/instances/iid-datasource-none/datasource (quiet=False)
2025-03-28 15:01:50,568 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/iid-datasource-none/datasource - wb: [644] 31 bytes
2025-03-28 15:01:50,569 - util.py[DEBUG]: Writing to /var/lib/cloud/data/previous-datasource - wb: [644] 31 bytes
2025-03-28 15:01:50,570 - util.py[DEBUG]: Reading from /var/lib/cloud/data/instance-id (quiet=False)
2025-03-28 15:01:50,571 - stages.py[DEBUG]: previous iid found to be NO_PREVIOUS_INSTANCE_ID
2025-03-28 15:01:50,571 - util.py[DEBUG]: Writing to /var/lib/cloud/data/instance-id - wb: [644] 20 bytes
2025-03-28 15:01:50,572 - util.py[DEBUG]: Writing to /run/cloud-init/.instance-id - wb: [644] 20 bytes
2025-03-28 15:01:50,573 - util.py[DEBUG]: Writing to /var/lib/cloud/data/previous-instance-id - wb: [644] 24 bytes
2025-03-28 15:01:50,576 - util.py[DEBUG]: Writing to /var/lib/cloud/instance/obj.pkl - wb: [400] 7226 bytes
2025-03-28 15:01:50,577 - main.py[DEBUG]: [net] init will now be targeting instance id: iid-datasource-none. new=True
2025-03-28 15:01:50,577 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg (quiet=False)
2025-03-28 15:01:50,578 - util.py[DEBUG]: Reading 3718 bytes from /etc/cloud/cloud.cfg
2025-03-28 15:01:50,578 - util.py[DEBUG]: Attempting to load yaml from string of length 3718 with allowed root types (<class 'dict'>,)
2025-03-28 15:01:50,607 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/curtin-preserve-sources.cfg (quiet=False)
2025-03-28 15:01:50,608 - util.py[DEBUG]: Reading 35 bytes from /etc/cloud/cloud.cfg.d/curtin-preserve-sources.cfg
2025-03-28 15:01:50,608 - util.py[DEBUG]: Attempting to load yaml from string of length 35 with allowed root types (<class 'dict'>,)
2025-03-28 15:01:50,609 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/99-installer.cfg (quiet=False)
2025-03-28 15:01:50,609 - util.py[DEBUG]: Reading 806 bytes from /etc/cloud/cloud.cfg.d/99-installer.cfg
2025-03-28 15:01:50,609 - util.py[DEBUG]: Attempting to load yaml from string of length 806 with allowed root types (<class 'dict'>,)
2025-03-28 15:01:50,612 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/90_dpkg.cfg (quiet=False)
2025-03-28 15:01:50,613 - util.py[DEBUG]: Reading 333 bytes from /etc/cloud/cloud.cfg.d/90_dpkg.cfg
2025-03-28 15:01:50,613 - util.py[DEBUG]: Attempting to load yaml from string of length 333 with allowed root types (<class 'dict'>,)
2025-03-28 15:01:50,616 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/90-installer-network.cfg (quiet=False)
2025-03-28 15:01:50,616 - util.py[DEBUG]: Reading 116 bytes from /etc/cloud/cloud.cfg.d/90-installer-network.cfg
2025-03-28 15:01:50,616 - util.py[DEBUG]: Attempting to load yaml from string of length 116 with allowed root types (<class 'dict'>,)
2025-03-28 15:01:50,617 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/20-disable-cc-dpkg-grub.cfg (quiet=False)
2025-03-28 15:01:50,618 - util.py[DEBUG]: Reading 28 bytes from /etc/cloud/cloud.cfg.d/20-disable-cc-dpkg-grub.cfg
2025-03-28 15:01:50,618 - util.py[DEBUG]: Attempting to load yaml from string of length 28 with allowed root types (<class 'dict'>,)
2025-03-28 15:01:50,618 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/05_logging.cfg (quiet=False)
2025-03-28 15:01:50,619 - util.py[DEBUG]: Reading 2071 bytes from /etc/cloud/cloud.cfg.d/05_logging.cfg
2025-03-28 15:01:50,619 - util.py[DEBUG]: Attempting to load yaml from string of length 2071 with allowed root types (<class 'dict'>,)
2025-03-28 15:01:50,623 - util.py[DEBUG]: Reading from /run/cloud-init/cloud.cfg (quiet=False)
2025-03-28 15:01:50,624 - util.py[DEBUG]: Attempting to load yaml from string of length 0 with allowed root types (<class 'dict'>,)
2025-03-28 15:01:50,624 - util.py[DEBUG]: loaded blob returned None, returning default.
2025-03-28 15:01:50,626 - util.py[DEBUG]: Reading from /sys/class/net/ens33/address (quiet=False)
2025-03-28 15:01:50,627 - util.py[DEBUG]: Reading 18 bytes from /sys/class/net/ens33/address
2025-03-28 15:01:50,627 - util.py[DEBUG]: Reading from /sys/class/net/lo/address (quiet=False)
2025-03-28 15:01:50,627 - util.py[DEBUG]: Reading 18 bytes from /sys/class/net/lo/address
2025-03-28 15:01:50,629 - util.py[DEBUG]: Reading from /sys/class/net/ens33/address (quiet=False)
2025-03-28 15:01:50,629 - util.py[DEBUG]: Reading 18 bytes from /sys/class/net/ens33/address
2025-03-28 15:01:50,629 - util.py[DEBUG]: Reading from /sys/class/net/lo/address (quiet=False)
2025-03-28 15:01:50,630 - util.py[DEBUG]: Reading 18 bytes from /sys/class/net/lo/address
2025-03-28 15:01:50,631 - atomic_helper.py[DEBUG]: Atomically writing to file /var/lib/cloud/instance/network-config.json (via temporary file /var/lib/cloud/instance/tmpe77psn72) - w: [600] 72 bytes/chars
2025-03-28 15:01:50,631 - util.py[DEBUG]: Creating symbolic link from '/run/cloud-init/network-config.json' => '/var/lib/cloud/instance/network-config.json'
2025-03-28 15:01:50,632 - util.py[DEBUG]: Reading from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-network-config-v2.json (quiet=False)
2025-03-28 15:01:50,632 - util.py[DEBUG]: Reading 17906 bytes from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-network-config-v2.json
2025-03-28 15:01:50,633 - schema.py[DEBUG]: Validating network-config with netplan API
2025-03-28 15:01:50,636 - util.py[DEBUG]: Writing to /run/cloud-init/tmp/tmpri8eprp8/etc/netplan/network-config.yaml - wb: [600] 86 bytes
2025-03-28 15:01:50,639 - stages.py[DEBUG]: Using distro class <class 'cloudinit.distros.ubuntu.Distro'>
2025-03-28 15:01:50,640 - util.py[DEBUG]: Reading from /sys/class/net/ens33/addr_assign_type (quiet=False)
2025-03-28 15:01:50,640 - util.py[DEBUG]: Reading 2 bytes from /sys/class/net/ens33/addr_assign_type
2025-03-28 15:01:50,641 - util.py[DEBUG]: Reading from /sys/class/net/ens33/uevent (quiet=False)
2025-03-28 15:01:50,641 - util.py[DEBUG]: Reading 26 bytes from /sys/class/net/ens33/uevent
2025-03-28 15:01:50,641 - util.py[DEBUG]: Reading from /sys/class/net/ens33/address (quiet=False)
2025-03-28 15:01:50,641 - util.py[DEBUG]: Reading 18 bytes from /sys/class/net/ens33/address
2025-03-28 15:01:50,642 - net[DEBUG]: ovs-vsctl not in PATH; not detecting Open vSwitch interfaces
2025-03-28 15:01:50,642 - util.py[DEBUG]: Reading from /sys/class/net/ens33/device/device (quiet=False)
2025-03-28 15:01:50,642 - util.py[DEBUG]: Reading 7 bytes from /sys/class/net/ens33/device/device
2025-03-28 15:01:50,643 - util.py[DEBUG]: Reading from /sys/class/net/lo/addr_assign_type (quiet=False)
2025-03-28 15:01:50,643 - util.py[DEBUG]: Reading 2 bytes from /sys/class/net/lo/addr_assign_type
2025-03-28 15:01:50,643 - util.py[DEBUG]: Reading from /sys/class/net/lo/uevent (quiet=False)
2025-03-28 15:01:50,643 - util.py[DEBUG]: Reading 23 bytes from /sys/class/net/lo/uevent
2025-03-28 15:01:50,644 - util.py[DEBUG]: Reading from /sys/class/net/lo/address (quiet=False)
2025-03-28 15:01:50,645 - util.py[DEBUG]: Reading 18 bytes from /sys/class/net/lo/address
2025-03-28 15:01:50,645 - util.py[DEBUG]: Reading from /sys/class/net/lo/device/device (quiet=False)
2025-03-28 15:01:50,645 - util.py[DEBUG]: Reading from /sys/class/net/ens33/type (quiet=False)
2025-03-28 15:01:50,645 - util.py[DEBUG]: Reading 2 bytes from /sys/class/net/ens33/type
2025-03-28 15:01:50,646 - util.py[DEBUG]: Reading from /sys/class/net/lo/type (quiet=False)
2025-03-28 15:01:50,646 - util.py[DEBUG]: Reading 4 bytes from /sys/class/net/lo/type
2025-03-28 15:01:50,646 - networking.py[DEBUG]: net: all expected physical devices present
2025-03-28 15:01:50,646 - stages.py[DEBUG]: applying net config names for {'ethernets': {'ens33': {'dhcp4': True}}, 'version': 2}
2025-03-28 15:01:50,646 - net[DEBUG]: no interfaces to rename
2025-03-28 15:01:50,647 - stages.py[INFO]: Applying network configuration from system_cfg bringup=True: {'ethernets': {'ens33': {'dhcp4': True}}, 'version': 2}
2025-03-28 15:01:50,647 - distros[DEBUG]: Selected renderer 'netplan' from priority list: ['netplan', 'eni', 'sysconfig']
2025-03-28 15:01:50,648 - network_state.py[DEBUG]: Passthrough netplan v2 config
2025-03-28 15:01:50,648 - netplan.py[DEBUG]: V2 to V2 passthrough
2025-03-28 15:01:50,651 - util.py[DEBUG]: Reading from /etc/netplan/50-cloud-init.yaml (quiet=False)
2025-03-28 15:01:50,652 - util.py[DEBUG]: Reading 64 bytes from /etc/netplan/50-cloud-init.yaml
2025-03-28 15:01:50,652 - util.py[DEBUG]: Attempting to load yaml from string of length 64 with allowed root types (<class 'dict'>,)
2025-03-28 15:01:50,654 - util.py[DEBUG]: Attempting to load yaml from string of length 390 with allowed root types (<class 'dict'>,)
2025-03-28 15:01:50,658 - netplan.py[DEBUG]: Rendered netplan config using netplan python API
2025-03-28 15:01:50,659 - netplan.py[DEBUG]: skipping call to `netplan generate`. reason: identical netplan config
2025-03-28 15:01:50,659 - subp.py[DEBUG]: Running command ['udevadm', 'test-builtin', 'net_setup_link', '/sys/class/net/ens33'] with allowed return codes [0] (shell=False, capture=True)
2025-03-28 15:01:50,670 - performance.py[DEBUG]: Running ['udevadm', 'test-builtin', 'net_setup_link', '/sys/class/net/ens33'] took 0.011 seconds
2025-03-28 15:01:50,671 - subp.py[DEBUG]: Running command ['udevadm', 'test-builtin', 'net_setup_link', '/sys/class/net/lo'] with allowed return codes [0] (shell=False, capture=True)
2025-03-28 15:01:50,681 - distros[DEBUG]: Bringing up newly configured network interfaces
2025-03-28 15:01:50,681 - activators.py[DEBUG]: Using selected activator: <class 'cloudinit.net.activators.NetplanActivator'> from priority: ['netplan', 'eni', 'network-manager', 'networkd']
2025-03-28 15:01:50,681 - subp.py[DEBUG]: Running command ['netplan', 'apply'] with allowed return codes [0] (shell=False, capture=True)
2025-03-28 15:01:53,614 - performance.py[DEBUG]: Running ['netplan', 'apply'] took 2.933 seconds
2025-03-28 15:01:53,615 - activators.py[DEBUG]: Received stderr output: 
** (generate:1635): WARNING **: 15:01:51.199: Permissions for /etc/netplan/01-network-manager-all.yaml are too open. Netplan configuration should NOT be accessible by others.

** (process:1633): WARNING **: 15:01:53.078: Permissions for /etc/netplan/01-network-manager-all.yaml are too open. Netplan configuration should NOT be accessible by others.

** (process:1633): WARNING **: 15:01:53.429: Permissions for /etc/netplan/01-network-manager-all.yaml are too open. Netplan configuration should NOT be accessible by others.

2025-03-28 15:01:53,615 - handlers.py[DEBUG]: start: init-network/setup-datasource: setting up datasource
2025-03-28 15:01:53,615 - handlers.py[DEBUG]: finish: init-network/setup-datasource: SUCCESS: setting up datasource
2025-03-28 15:01:53,616 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/iid-datasource-none/user-data.txt - wb: [600] 594 bytes
2025-03-28 15:01:53,618 - util.py[DEBUG]: Attempting to load yaml from string of length 594 with allowed root types (<class 'dict'>,)
2025-03-28 15:01:53,632 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/iid-datasource-none/user-data.txt.i - wb: [600] 899 bytes
2025-03-28 15:01:53,633 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/iid-datasource-none/vendor-data.txt - wb: [600] 0 bytes
2025-03-28 15:01:53,637 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/iid-datasource-none/vendor-data.txt.i - wb: [600] 308 bytes
2025-03-28 15:01:53,638 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/iid-datasource-none/vendor-data2.txt - wb: [600] 0 bytes
2025-03-28 15:01:53,643 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/iid-datasource-none/vendor-data2.txt.i - wb: [600] 308 bytes
2025-03-28 15:01:53,646 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/iid-datasource-none/sem/consume_data - wb: [644] 25 bytes
2025-03-28 15:01:53,647 - helpers.py[DEBUG]: Running consume_data using lock (<FileLock using file '/var/lib/cloud/instances/iid-datasource-none/sem/consume_data'>)
2025-03-28 15:01:53,647 - handlers.py[DEBUG]: start: init-network/consume-user-data: reading and applying user-data
2025-03-28 15:01:53,649 - stages.py[DEBUG]: Added default handler for {'text/cloud-config', 'text/cloud-config-jsonp'} from CloudConfigPartHandler: [['text/cloud-config', 'text/cloud-config-jsonp']]
2025-03-28 15:01:53,649 - stages.py[DEBUG]: Added default handler for {'text/x-shellscript'} from ShellScriptPartHandler: [['text/x-shellscript']]
2025-03-28 15:01:53,649 - stages.py[DEBUG]: Added default handler for {'text/x-shellscript-per-boot'} from ShellScriptByFreqPartHandler: [['text/x-shellscript-per-boot']]
2025-03-28 15:01:53,649 - stages.py[DEBUG]: Added default handler for {'text/x-shellscript-per-instance'} from ShellScriptByFreqPartHandler: [['text/x-shellscript-per-instance']]
2025-03-28 15:01:53,649 - stages.py[DEBUG]: Added default handler for {'text/x-shellscript-per-once'} from ShellScriptByFreqPartHandler: [['text/x-shellscript-per-once']]
2025-03-28 15:01:53,650 - stages.py[DEBUG]: Added default handler for {'text/cloud-boothook'} from BootHookPartHandler: [['text/cloud-boothook']]
2025-03-28 15:01:53,650 - stages.py[DEBUG]: Added default handler for {'text/jinja2'} from JinjaTemplatePartHandler: [['text/jinja2']]
2025-03-28 15:01:53,651 - handlers[DEBUG]: Calling handler CloudConfigPartHandler: [['text/cloud-config', 'text/cloud-config-jsonp']] (__begin__, None, 3) with frequency once-per-instance
2025-03-28 15:01:53,651 - handlers[DEBUG]: Calling handler ShellScriptPartHandler: [['text/x-shellscript']] (__begin__, None, 2) with frequency once-per-instance
2025-03-28 15:01:53,651 - handlers[DEBUG]: Calling handler ShellScriptByFreqPartHandler: [['text/x-shellscript-per-boot']] (__begin__, None, 2) with frequency once-per-instance
2025-03-28 15:01:53,651 - handlers[DEBUG]: Calling handler ShellScriptByFreqPartHandler: [['text/x-shellscript-per-instance']] (__begin__, None, 2) with frequency once-per-instance
2025-03-28 15:01:53,652 - handlers[DEBUG]: Calling handler ShellScriptByFreqPartHandler: [['text/x-shellscript-per-once']] (__begin__, None, 2) with frequency once-per-instance
2025-03-28 15:01:53,652 - handlers[DEBUG]: Calling handler BootHookPartHandler: [['text/cloud-boothook']] (__begin__, None, 2) with frequency once-per-instance
2025-03-28 15:01:53,652 - handlers[DEBUG]: Calling handler JinjaTemplatePartHandler: [['text/jinja2']] (__begin__, None, 3) with frequency once-per-instance
2025-03-28 15:01:53,652 - handlers[DEBUG]: {'MIME-Version': '1.0', 'Content-Type': 'text/cloud-config', 'Content-Disposition': 'attachment; filename="part-001"'}
2025-03-28 15:01:53,652 - handlers[DEBUG]: Calling handler CloudConfigPartHandler: [['text/cloud-config', 'text/cloud-config-jsonp']] (text/cloud-config, part-001, 3) with frequency once-per-instance
2025-03-28 15:01:53,653 - util.py[DEBUG]: Attempting to load yaml from string of length 594 with allowed root types (<class 'dict'>,)
2025-03-28 15:01:53,665 - cloud_config.py[DEBUG]: Merging by applying [('dict', ['replace']), ('list', []), ('str', [])]
2025-03-28 15:01:53,666 - handlers[DEBUG]: Calling handler CloudConfigPartHandler: [['text/cloud-config', 'text/cloud-config-jsonp']] (__end__, None, 3) with frequency once-per-instance
2025-03-28 15:01:53,675 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/iid-datasource-none/cloud-config.txt - wb: [600] 654 bytes
2025-03-28 15:01:53,679 - handlers[DEBUG]: Calling handler ShellScriptPartHandler: [['text/x-shellscript']] (__end__, None, 2) with frequency once-per-instance
2025-03-28 15:01:53,679 - handlers[DEBUG]: Calling handler ShellScriptByFreqPartHandler: [['text/x-shellscript-per-boot']] (__end__, None, 2) with frequency once-per-instance
2025-03-28 15:01:53,680 - handlers[DEBUG]: Calling handler ShellScriptByFreqPartHandler: [['text/x-shellscript-per-instance']] (__end__, None, 2) with frequency once-per-instance
2025-03-28 15:01:53,680 - handlers[DEBUG]: Calling handler ShellScriptByFreqPartHandler: [['text/x-shellscript-per-once']] (__end__, None, 2) with frequency once-per-instance
2025-03-28 15:01:53,680 - handlers[DEBUG]: Calling handler BootHookPartHandler: [['text/cloud-boothook']] (__end__, None, 2) with frequency once-per-instance
2025-03-28 15:01:53,682 - handlers[DEBUG]: Calling handler JinjaTemplatePartHandler: [['text/jinja2']] (__end__, None, 3) with frequency once-per-instance
2025-03-28 15:01:53,682 - handlers.py[DEBUG]: finish: init-network/consume-user-data: SUCCESS: reading and applying user-data
2025-03-28 15:01:53,684 - handlers.py[DEBUG]: start: init-network/consume-vendor-data: reading and applying vendor-data
2025-03-28 15:01:53,684 - stages.py[DEBUG]: no vendordata from datasource
2025-03-28 15:01:53,685 - handlers.py[DEBUG]: finish: init-network/consume-vendor-data: SUCCESS: reading and applying vendor-data
2025-03-28 15:01:53,685 - handlers.py[DEBUG]: start: init-network/consume-vendor-data2: reading and applying vendor-data2
2025-03-28 15:01:53,685 - stages.py[DEBUG]: no vendordata2 from datasource
2025-03-28 15:01:53,685 - handlers.py[DEBUG]: finish: init-network/consume-vendor-data2: SUCCESS: reading and applying vendor-data2
2025-03-28 15:01:53,686 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg (quiet=False)
2025-03-28 15:01:53,687 - util.py[DEBUG]: Reading 3718 bytes from /etc/cloud/cloud.cfg
2025-03-28 15:01:53,687 - util.py[DEBUG]: Attempting to load yaml from string of length 3718 with allowed root types (<class 'dict'>,)
2025-03-28 15:01:53,745 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/curtin-preserve-sources.cfg (quiet=False)
2025-03-28 15:01:53,746 - util.py[DEBUG]: Reading 35 bytes from /etc/cloud/cloud.cfg.d/curtin-preserve-sources.cfg
2025-03-28 15:01:53,746 - util.py[DEBUG]: Attempting to load yaml from string of length 35 with allowed root types (<class 'dict'>,)
2025-03-28 15:01:53,750 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/99-installer.cfg (quiet=False)
2025-03-28 15:01:53,750 - util.py[DEBUG]: Reading 806 bytes from /etc/cloud/cloud.cfg.d/99-installer.cfg
2025-03-28 15:01:53,750 - util.py[DEBUG]: Attempting to load yaml from string of length 806 with allowed root types (<class 'dict'>,)
2025-03-28 15:01:53,759 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/90_dpkg.cfg (quiet=False)
2025-03-28 15:01:53,760 - util.py[DEBUG]: Reading 333 bytes from /etc/cloud/cloud.cfg.d/90_dpkg.cfg
2025-03-28 15:01:53,760 - util.py[DEBUG]: Attempting to load yaml from string of length 333 with allowed root types (<class 'dict'>,)
2025-03-28 15:01:53,767 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/90-installer-network.cfg (quiet=False)
2025-03-28 15:01:53,769 - util.py[DEBUG]: Reading 116 bytes from /etc/cloud/cloud.cfg.d/90-installer-network.cfg
2025-03-28 15:01:53,770 - util.py[DEBUG]: Attempting to load yaml from string of length 116 with allowed root types (<class 'dict'>,)
2025-03-28 15:01:53,774 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/20-disable-cc-dpkg-grub.cfg (quiet=False)
2025-03-28 15:01:53,774 - util.py[DEBUG]: Reading 28 bytes from /etc/cloud/cloud.cfg.d/20-disable-cc-dpkg-grub.cfg
2025-03-28 15:01:53,774 - util.py[DEBUG]: Attempting to load yaml from string of length 28 with allowed root types (<class 'dict'>,)
2025-03-28 15:01:53,778 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/05_logging.cfg (quiet=False)
2025-03-28 15:01:53,778 - util.py[DEBUG]: Reading 2071 bytes from /etc/cloud/cloud.cfg.d/05_logging.cfg
2025-03-28 15:01:53,778 - util.py[DEBUG]: Attempting to load yaml from string of length 2071 with allowed root types (<class 'dict'>,)
2025-03-28 15:01:53,795 - util.py[DEBUG]: Reading from /run/cloud-init/cloud.cfg (quiet=False)
2025-03-28 15:01:53,795 - util.py[DEBUG]: Attempting to load yaml from string of length 0 with allowed root types (<class 'dict'>,)
2025-03-28 15:01:53,795 - util.py[DEBUG]: loaded blob returned None, returning default.
2025-03-28 15:01:53,796 - util.py[DEBUG]: Reading from /var/lib/cloud/instance/cloud-config.txt (quiet=False)
2025-03-28 15:01:53,796 - util.py[DEBUG]: Reading 654 bytes from /var/lib/cloud/instance/cloud-config.txt
2025-03-28 15:01:53,797 - util.py[DEBUG]: Attempting to load yaml from string of length 654 with allowed root types (<class 'dict'>,)
2025-03-28 15:01:53,822 - atomic_helper.py[DEBUG]: Atomically writing to file /run/cloud-init/combined-cloud-config.json (via temporary file /run/cloud-init/tmpv3lio0n1) - w: [600] 7093 bytes/chars
2025-03-28 15:01:53,823 - util.py[DEBUG]: Reading from /run/cloud-init/instance-data-sensitive.json (quiet=False)
2025-03-28 15:01:53,824 - util.py[DEBUG]: Reading 9865 bytes from /run/cloud-init/instance-data-sensitive.json
2025-03-28 15:01:53,828 - atomic_helper.py[DEBUG]: Atomically writing to file /run/cloud-init/instance-data-sensitive.json (via temporary file /run/cloud-init/tmptbi38p27) - w: [600] 12064 bytes/chars
2025-03-28 15:01:53,829 - util.py[DEBUG]: Reading from /var/lib/cloud/instance/cloud-config.txt (quiet=False)
2025-03-28 15:01:53,831 - util.py[DEBUG]: Reading 654 bytes from /var/lib/cloud/instance/cloud-config.txt
2025-03-28 15:01:53,845 - util.py[DEBUG]: Reading from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2025-03-28 15:01:53,895 - util.py[DEBUG]: Reading 149679 bytes from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2025-03-28 15:01:54,021 - performance.py[DEBUG]: Validating schema took 0.176 seconds
2025-03-28 15:01:54,024 - util.py[DEBUG]: Reading from /var/lib/cloud/instance/cloud-config.txt (quiet=False)
2025-03-28 15:01:54,025 - util.py[DEBUG]: Reading 654 bytes from /var/lib/cloud/instance/cloud-config.txt
2025-03-28 15:01:54,025 - util.py[DEBUG]: Attempting to load yaml from string of length 654 with allowed root types (<class 'dict'>,)
2025-03-28 15:01:54,041 - handlers.py[DEBUG]: start: init-network/activate-datasource: activating datasource
2025-03-28 15:01:54,044 - util.py[DEBUG]: Writing to /var/lib/cloud/instance/obj.pkl - wb: [400] 10104 bytes
2025-03-28 15:01:54,047 - handlers.py[DEBUG]: finish: init-network/activate-datasource: SUCCESS: activating datasource
2025-03-28 15:01:54,048 - main.py[DEBUG]: no di_report found in config.
2025-03-28 15:01:54,322 - stages.py[DEBUG]: Using distro class <class 'cloudinit.distros.ubuntu.Distro'>
2025-03-28 15:01:54,340 - modules.py[INFO]: Skipping modules 'bootcmd,disk_setup,update_etc_hosts,ca_certs,rsyslog' because no applicable config is provided.
2025-03-28 15:01:54,341 - modules.py[DEBUG]: Running module seed_random (<module 'cloudinit.config.cc_seed_random' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_seed_random.py'>) with frequency once-per-instance
2025-03-28 15:01:54,343 - handlers.py[DEBUG]: start: init-network/config-seed_random: running config-seed_random with frequency once-per-instance
2025-03-28 15:01:54,344 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/iid-datasource-none/sem/config_seed_random - wb: [644] 25 bytes
2025-03-28 15:01:54,348 - helpers.py[DEBUG]: Running config-seed_random using lock (<FileLock using file '/var/lib/cloud/instances/iid-datasource-none/sem/config_seed_random'>)
2025-03-28 15:01:54,348 - cc_seed_random.py[DEBUG]: no command provided
2025-03-28 15:01:54,348 - handlers.py[DEBUG]: finish: init-network/config-seed_random: SUCCESS: config-seed_random ran successfully and took 0.004 seconds
2025-03-28 15:01:54,348 - modules.py[DEBUG]: Running module write_files (<module 'cloudinit.config.cc_write_files' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_write_files.py'>) with frequency once-per-instance
2025-03-28 15:01:54,351 - handlers.py[DEBUG]: start: init-network/config-write_files: running config-write_files with frequency once-per-instance
2025-03-28 15:01:54,352 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/iid-datasource-none/sem/config_write_files - wb: [644] 25 bytes
2025-03-28 15:01:54,356 - helpers.py[DEBUG]: Running config-write_files using lock (<FileLock using file '/var/lib/cloud/instances/iid-datasource-none/sem/config_write_files'>)
2025-03-28 15:01:54,356 - cc_write_files.py[DEBUG]: Skipping module named write_files, no/empty 'write_files' key in configuration
2025-03-28 15:01:54,357 - handlers.py[DEBUG]: finish: init-network/config-write_files: SUCCESS: config-write_files ran successfully and took 0.005 seconds
2025-03-28 15:01:54,357 - modules.py[DEBUG]: Running module growpart (<module 'cloudinit.config.cc_growpart' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_growpart.py'>) with frequency always
2025-03-28 15:01:54,358 - handlers.py[DEBUG]: start: init-network/config-growpart: running config-growpart with frequency always
2025-03-28 15:01:54,358 - helpers.py[DEBUG]: Running config-growpart using lock (<cloudinit.helpers.DummyLock object at 0x73344fc3c9b0>)
2025-03-28 15:01:54,358 - cc_growpart.py[DEBUG]: growpart disabled: mode=off
2025-03-28 15:01:54,358 - handlers.py[DEBUG]: finish: init-network/config-growpart: SUCCESS: config-growpart ran successfully and took 0.000 seconds
2025-03-28 15:01:54,359 - modules.py[DEBUG]: Running module resizefs (<module 'cloudinit.config.cc_resizefs' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_resizefs.py'>) with frequency always
2025-03-28 15:01:54,359 - handlers.py[DEBUG]: start: init-network/config-resizefs: running config-resizefs with frequency always
2025-03-28 15:01:54,360 - helpers.py[DEBUG]: Running config-resizefs using lock (<cloudinit.helpers.DummyLock object at 0x73344fc3c9b0>)
2025-03-28 15:01:54,360 - cc_resizefs.py[DEBUG]: Skipping module named resizefs, resizing disabled
2025-03-28 15:01:54,362 - handlers.py[DEBUG]: finish: init-network/config-resizefs: SUCCESS: config-resizefs ran successfully and took 0.002 seconds
2025-03-28 15:01:54,362 - modules.py[DEBUG]: Running module mounts (<module 'cloudinit.config.cc_mounts' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_mounts.py'>) with frequency once-per-instance
2025-03-28 15:01:54,363 - handlers.py[DEBUG]: start: init-network/config-mounts: running config-mounts with frequency once-per-instance
2025-03-28 15:01:54,363 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/iid-datasource-none/sem/config_mounts - wb: [644] 25 bytes
2025-03-28 15:01:54,367 - helpers.py[DEBUG]: Running config-mounts using lock (<FileLock using file '/var/lib/cloud/instances/iid-datasource-none/sem/config_mounts'>)
2025-03-28 15:01:54,367 - cc_mounts.py[DEBUG]: mounts configuration is []
2025-03-28 15:01:54,367 - util.py[DEBUG]: Reading from /etc/fstab (quiet=False)
2025-03-28 15:01:54,368 - util.py[DEBUG]: Reading 473 bytes from /etc/fstab
2025-03-28 15:01:54,372 - cc_mounts.py[DEBUG]: Attempting to determine the real name of ephemeral0
2025-03-28 15:01:54,372 - cc_mounts.py[DEBUG]: changed ephemeral0 => None
2025-03-28 15:01:54,372 - cc_mounts.py[DEBUG]: Ignoring nonexistent default named mount ephemeral0
2025-03-28 15:01:54,373 - cc_mounts.py[DEBUG]: Attempting to determine the real name of swap
2025-03-28 15:01:54,373 - cc_mounts.py[DEBUG]: changed swap => None
2025-03-28 15:01:54,373 - cc_mounts.py[DEBUG]: Ignoring nonexistent default named mount swap
2025-03-28 15:01:54,373 - cc_mounts.py[DEBUG]: no need to setup swap
2025-03-28 15:01:54,373 - cc_mounts.py[DEBUG]: No modifications to fstab needed
2025-03-28 15:01:54,374 - handlers.py[DEBUG]: finish: init-network/config-mounts: SUCCESS: config-mounts ran successfully and took 0.010 seconds
2025-03-28 15:01:54,374 - modules.py[DEBUG]: Running module set_hostname (<module 'cloudinit.config.cc_set_hostname' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_set_hostname.py'>) with frequency once-per-instance
2025-03-28 15:01:54,380 - handlers.py[DEBUG]: start: init-network/config-set_hostname: running config-set_hostname with frequency once-per-instance
2025-03-28 15:01:54,381 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/iid-datasource-none/sem/config_set_hostname - wb: [644] 25 bytes
2025-03-28 15:01:54,386 - helpers.py[DEBUG]: Running config-set_hostname using lock (<FileLock using file '/var/lib/cloud/instances/iid-datasource-none/sem/config_set_hostname'>)
2025-03-28 15:01:54,387 - cc_set_hostname.py[DEBUG]: Configuration option 'preserve_hostname' is set, not setting the hostname in module set_hostname
2025-03-28 15:01:54,387 - handlers.py[DEBUG]: finish: init-network/config-set_hostname: SUCCESS: config-set_hostname ran successfully and took 0.006 seconds
2025-03-28 15:01:54,387 - modules.py[DEBUG]: Running module update_hostname (<module 'cloudinit.config.cc_update_hostname' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_update_hostname.py'>) with frequency always
2025-03-28 15:01:54,389 - handlers.py[DEBUG]: start: init-network/config-update_hostname: running config-update_hostname with frequency always
2025-03-28 15:01:54,389 - helpers.py[DEBUG]: Running config-update_hostname using lock (<cloudinit.helpers.DummyLock object at 0x73344fc3d160>)
2025-03-28 15:01:54,389 - cc_update_hostname.py[DEBUG]: Configuration option 'preserve_hostname' is set, not updating the hostname in module update_hostname
2025-03-28 15:01:54,389 - handlers.py[DEBUG]: finish: init-network/config-update_hostname: SUCCESS: config-update_hostname ran successfully and took 0.000 seconds
2025-03-28 15:01:54,390 - modules.py[DEBUG]: Running module users_groups (<module 'cloudinit.config.cc_users_groups' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_users_groups.py'>) with frequency once-per-instance
2025-03-28 15:01:54,398 - handlers.py[DEBUG]: start: init-network/config-users_groups: running config-users_groups with frequency once-per-instance
2025-03-28 15:01:54,399 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/iid-datasource-none/sem/config_users_groups - wb: [644] 25 bytes
2025-03-28 15:01:54,401 - helpers.py[DEBUG]: Running config-users_groups using lock (<FileLock using file '/var/lib/cloud/instances/iid-datasource-none/sem/config_users_groups'>)
2025-03-28 15:01:55,626 - util.py[DEBUG]: Reading from /etc/os-release (quiet=True)
2025-03-28 15:01:55,629 - util.py[DEBUG]: Reading 400 bytes from /etc/os-release
2025-03-28 15:01:55,630 - util.py[DEBUG]: Reading from /etc/system-image/channel.ini (quiet=True)
2025-03-28 15:01:55,631 - util.py[DEBUG]: Reading 0 bytes from /etc/system-image/channel.ini
2025-03-28 15:01:55,633 - distros[DEBUG]: Adding user rajesh
2025-03-28 15:01:55,633 - subp.py[DEBUG]: Running command ['useradd', 'rajesh', '--comment', 'Rajesh', '--groups', 'adm,cdrom,dip,lpadmin,plugdev,sudo,users', '--password', 'REDACTED', '--shell', '/bin/bash', '-m'] with allowed return codes [0] (shell=False, capture=True)
2025-03-28 15:01:55,996 - performance.py[DEBUG]: Running ['useradd', 'rajesh', '--comment', 'Rajesh', '--groups', 'adm,cdrom,dip,lpadmin,plugdev,sudo,users', '--password', 'REDACTED', '--shell', '/bin/bash', '-m'] took 0.362 seconds
2025-03-28 15:01:55,997 - subp.py[DEBUG]: Running command ['passwd', '-u', 'rajesh'] with allowed return codes [0, 3] (shell=False, capture=True)
2025-03-28 15:01:56,081 - performance.py[DEBUG]: Running ['passwd', '-u', 'rajesh'] took 0.084 seconds
2025-03-28 15:01:56,082 - handlers.py[DEBUG]: finish: init-network/config-users_groups: SUCCESS: config-users_groups ran successfully and took 1.683 seconds
2025-03-28 15:01:56,083 - modules.py[DEBUG]: Running module ssh (<module 'cloudinit.config.cc_ssh' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_ssh.py'>) with frequency once-per-instance
2025-03-28 15:01:56,083 - handlers.py[DEBUG]: start: init-network/config-ssh: running config-ssh with frequency once-per-instance
2025-03-28 15:01:56,084 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/iid-datasource-none/sem/config_ssh - wb: [644] 25 bytes
2025-03-28 15:01:56,085 - helpers.py[DEBUG]: Running config-ssh using lock (<FileLock using file '/var/lib/cloud/instances/iid-datasource-none/sem/config_ssh'>)
2025-03-28 15:01:56,120 - util.py[DEBUG]: Reading from /proc/sys/crypto/fips_enabled (quiet=False)
2025-03-28 15:01:56,121 - subp.py[DEBUG]: Running command ['ssh-keygen', '-t', 'rsa', '-N', '', '-f', '/etc/ssh/ssh_host_rsa_key'] with allowed return codes [0] (shell=False, capture=True)
2025-03-28 15:01:58,627 - performance.py[DEBUG]: Running ['ssh-keygen', '-t', 'rsa', '-N', '', '-f', '/etc/ssh/ssh_host_rsa_key'] took 2.506 seconds
2025-03-28 15:01:58,629 - subp.py[DEBUG]: Running command ['ssh-keygen', '-t', 'ecdsa', '-N', '', '-f', '/etc/ssh/ssh_host_ecdsa_key'] with allowed return codes [0] (shell=False, capture=True)
2025-03-28 15:01:58,681 - performance.py[DEBUG]: Running ['ssh-keygen', '-t', 'ecdsa', '-N', '', '-f', '/etc/ssh/ssh_host_ecdsa_key'] took 0.052 seconds
2025-03-28 15:01:58,682 - subp.py[DEBUG]: Running command ['ssh-keygen', '-t', 'ed25519', '-N', '', '-f', '/etc/ssh/ssh_host_ed25519_key'] with allowed return codes [0] (shell=False, capture=True)
2025-03-28 15:01:58,710 - performance.py[DEBUG]: Running ['ssh-keygen', '-t', 'ed25519', '-N', '', '-f', '/etc/ssh/ssh_host_ed25519_key'] took 0.027 seconds
2025-03-28 15:01:58,711 - util.py[DEBUG]: Reading from /etc/ssh/ssh_host_ed25519_key.pub (quiet=False)
2025-03-28 15:01:58,711 - util.py[DEBUG]: Reading 93 bytes from /etc/ssh/ssh_host_ed25519_key.pub
2025-03-28 15:01:58,712 - util.py[DEBUG]: Reading from /etc/ssh/ssh_host_rsa_key.pub (quiet=False)
2025-03-28 15:01:58,712 - util.py[DEBUG]: Reading 565 bytes from /etc/ssh/ssh_host_rsa_key.pub
2025-03-28 15:01:58,712 - util.py[DEBUG]: Reading from /etc/ssh/ssh_host_ecdsa_key.pub (quiet=False)
2025-03-28 15:01:58,712 - util.py[DEBUG]: Reading 173 bytes from /etc/ssh/ssh_host_ecdsa_key.pub
2025-03-28 15:01:58,747 - util.py[DEBUG]: Writing to /root/.ssh/authorized_keys - wb: [600] 0 bytes
2025-03-28 15:01:58,757 - performance.py[DEBUG]: Writing file took 0.010 seconds
2025-03-28 15:01:58,758 - util.py[DEBUG]: Changing the ownership of /root/.ssh/authorized_keys to 0:0
2025-03-28 15:01:58,758 - util.py[DEBUG]: Reading from /root/.ssh/authorized_keys (quiet=False)
2025-03-28 15:01:58,758 - util.py[DEBUG]: Reading 0 bytes from /root/.ssh/authorized_keys
2025-03-28 15:01:58,759 - util.py[DEBUG]: Writing to /root/.ssh/authorized_keys - wb: [600] 0 bytes
2025-03-28 15:01:58,760 - handlers.py[DEBUG]: finish: init-network/config-ssh: SUCCESS: config-ssh ran successfully and took 2.676 seconds
2025-03-28 15:01:58,760 - modules.py[DEBUG]: Running module set_passwords (<module 'cloudinit.config.cc_set_passwords' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_set_passwords.py'>) with frequency once-per-instance
2025-03-28 15:01:58,761 - handlers.py[DEBUG]: start: init-network/config-set_passwords: running config-set_passwords with frequency once-per-instance
2025-03-28 15:01:58,762 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/iid-datasource-none/sem/config_set_passwords - wb: [644] 25 bytes
2025-03-28 15:01:58,763 - helpers.py[DEBUG]: Running config-set_passwords using lock (<FileLock using file '/var/lib/cloud/instances/iid-datasource-none/sem/config_set_passwords'>)
2025-03-28 15:01:58,763 - cc_set_passwords.py[DEBUG]: Leaving SSH config 'PasswordAuthentication' unchanged. ssh_pwauth=None
2025-03-28 15:01:58,763 - handlers.py[DEBUG]: finish: init-network/config-set_passwords: SUCCESS: config-set_passwords ran successfully and took 0.002 seconds
2025-03-28 15:01:58,763 - main.py[DEBUG]: Ran 10 modules with 0 failures
2025-03-28 15:01:58,764 - util.py[DEBUG]: Reading from /proc/uptime (quiet=False)
2025-03-28 15:01:58,764 - util.py[DEBUG]: Reading 12 bytes from /proc/uptime
2025-03-28 15:01:58,765 - atomic_helper.py[DEBUG]: Atomically writing to file /var/lib/cloud/data/status.json (via temporary file /var/lib/cloud/data/tmp92iggf8l) - w: [644] 497 bytes/chars
2025-03-28 15:01:58,766 - performance.py[DEBUG]: cloud-init stage: 'init-network' took 9.034 seconds
2025-03-28 15:01:58,766 - handlers.py[DEBUG]: finish: init-network: SUCCESS: searching for network datasources
2025-03-28 15:02:00,451 - log_util.py[DEBUG]: Cloud-init v. 24.4-0ubuntu1~24.04.2 running 'modules:config' at Fri, 28 Mar 2025 15:02:00 +0000. Up 79.58 seconds.
2025-03-28 15:02:00,453 - main.py[INFO]: PID [1] started cloud-init 'modules:config'.
2025-03-28 15:02:00,575 - stages.py[DEBUG]: Using distro class <class 'cloudinit.distros.ubuntu.Distro'>
2025-03-28 15:02:00,581 - modules.py[INFO]: Skipping modules 'wireguard,snap,ubuntu_autoinstall,keyboard,apt_pipelining,ubuntu_pro,ntp,disable_ec2_metadata,runcmd' because no applicable config is provided.
2025-03-28 15:02:00,582 - modules.py[DEBUG]: Running module ssh_import_id (<module 'cloudinit.config.cc_ssh_import_id' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_ssh_import_id.py'>) with frequency once-per-instance
2025-03-28 15:02:00,582 - handlers.py[DEBUG]: start: modules-config/config-ssh_import_id: running config-ssh_import_id with frequency once-per-instance
2025-03-28 15:02:00,583 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/iid-datasource-none/sem/config_ssh_import_id - wb: [644] 25 bytes
2025-03-28 15:02:00,585 - helpers.py[DEBUG]: Running config-ssh_import_id using lock (<FileLock using file '/var/lib/cloud/instances/iid-datasource-none/sem/config_ssh_import_id'>)
2025-03-28 15:02:00,586 - cc_ssh_import_id.py[DEBUG]: Skipping module named ssh_import_id, no 'ssh_import_id' directives found.
2025-03-28 15:02:00,586 - handlers.py[DEBUG]: finish: modules-config/config-ssh_import_id: SUCCESS: config-ssh_import_id ran successfully and took 0.004 seconds
2025-03-28 15:02:00,586 - modules.py[DEBUG]: Running module locale (<module 'cloudinit.config.cc_locale' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_locale.py'>) with frequency once-per-instance
2025-03-28 15:02:00,586 - handlers.py[DEBUG]: start: modules-config/config-locale: running config-locale with frequency once-per-instance
2025-03-28 15:02:00,587 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/iid-datasource-none/sem/config_locale - wb: [644] 25 bytes
2025-03-28 15:02:00,588 - helpers.py[DEBUG]: Running config-locale using lock (<FileLock using file '/var/lib/cloud/instances/iid-datasource-none/sem/config_locale'>)
2025-03-28 15:02:00,588 - util.py[DEBUG]: Reading from /etc/default/locale (quiet=False)
2025-03-28 15:02:00,588 - util.py[DEBUG]: Reading 13 bytes from /etc/default/locale
2025-03-28 15:02:00,588 - cc_locale.py[DEBUG]: Setting locale to en_US.UTF-8
2025-03-28 15:02:00,588 - debian.py[DEBUG]: System locale set to C.UTF-8 via /etc/default/locale
2025-03-28 15:02:00,588 - debian.py[DEBUG]: Generating locales for en_US.UTF-8
2025-03-28 15:02:00,589 - subp.py[DEBUG]: Running command ['locale-gen', 'en_US.UTF-8'] with allowed return codes [0] (shell=False, capture=False)
2025-03-28 15:02:07,138 - performance.py[DEBUG]: Running ['locale-gen', 'en_US.UTF-8'] took 7.912 seconds
2025-03-28 15:02:07,139 - debian.py[DEBUG]: Updating /etc/default/locale with locale setting LANG=en_US.UTF-8
2025-03-28 15:02:07,139 - subp.py[DEBUG]: Running command ['update-locale', '--locale-file=/etc/default/locale', 'LANG=en_US.UTF-8'] with allowed return codes [0] (shell=False, capture=False)
2025-03-28 15:02:07,235 - performance.py[DEBUG]: Running ['update-locale', '--locale-file=/etc/default/locale', 'LANG=en_US.UTF-8'] took 0.096 seconds
2025-03-28 15:02:07,236 - handlers.py[DEBUG]: finish: modules-config/config-locale: SUCCESS: config-locale ran successfully and took 8.012 seconds
2025-03-28 15:02:07,236 - modules.py[DEBUG]: Running module grub_dpkg (<module 'cloudinit.config.cc_grub_dpkg' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_grub_dpkg.py'>) with frequency once-per-instance
2025-03-28 15:02:07,237 - handlers.py[DEBUG]: start: modules-config/config-grub_dpkg: running config-grub_dpkg with frequency once-per-instance
2025-03-28 15:02:07,237 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/iid-datasource-none/sem/config_grub_dpkg - wb: [644] 24 bytes
2025-03-28 15:02:07,239 - helpers.py[DEBUG]: Running config-grub_dpkg using lock (<FileLock using file '/var/lib/cloud/instances/iid-datasource-none/sem/config_grub_dpkg'>)
2025-03-28 15:02:07,239 - cc_grub_dpkg.py[DEBUG]: grub_dpkg disabled by config grub_dpkg/enabled=False
2025-03-28 15:02:07,239 - handlers.py[DEBUG]: finish: modules-config/config-grub_dpkg: SUCCESS: config-grub_dpkg ran successfully and took 0.002 seconds
2025-03-28 15:02:07,239 - modules.py[DEBUG]: Running module apt_configure (<module 'cloudinit.config.cc_apt_configure' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_apt_configure.py'>) with frequency once-per-instance
2025-03-28 15:02:07,240 - handlers.py[DEBUG]: start: modules-config/config-apt_configure: running config-apt_configure with frequency once-per-instance
2025-03-28 15:02:07,240 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/iid-datasource-none/sem/config_apt_configure - wb: [644] 25 bytes
2025-03-28 15:02:07,241 - helpers.py[DEBUG]: Running config-apt_configure using lock (<FileLock using file '/var/lib/cloud/instances/iid-datasource-none/sem/config_apt_configure'>)
2025-03-28 15:02:07,242 - cc_apt_configure.py[DEBUG]: debconf_selections was not set in config
2025-03-28 15:02:07,243 - cc_apt_configure.py[DEBUG]: handling apt config: {'preserve_sources_list': True}
2025-03-28 15:02:07,243 - subp.py[DEBUG]: Running command ['lsb_release', '--all'] with allowed return codes [0] (shell=False, capture=True)
2025-03-28 15:02:07,274 - performance.py[DEBUG]: Running ['lsb_release', '--all'] took 0.031 seconds
2025-03-28 15:02:07,274 - subp.py[DEBUG]: Running command ['dpkg', '--print-architecture'] with allowed return codes [0] (shell=False, capture=True)
2025-03-28 15:02:07,413 - performance.py[DEBUG]: Running ['dpkg', '--print-architecture'] took 0.139 seconds
2025-03-28 15:02:07,414 - cc_apt_configure.py[DEBUG]: got primary mirror: None
2025-03-28 15:02:07,414 - cc_apt_configure.py[DEBUG]: got security mirror: None
2025-03-28 15:02:07,414 - util.py[DEBUG]: search for mirror in candidates: '[]'
2025-03-28 15:02:07,415 - util.py[DEBUG]: search for mirror in candidates: '[]'
2025-03-28 15:02:07,415 - distros[DEBUG]: filtered distro mirror info: {'primary': 'http://archive.ubuntu.com/ubuntu', 'security': 'http://security.ubuntu.com/ubuntu'}
2025-03-28 15:02:07,415 - cc_apt_configure.py[DEBUG]: Apt Mirror info: {'primary': 'http://archive.ubuntu.com/ubuntu', 'security': 'http://security.ubuntu.com/ubuntu', 'PRIMARY': 'http://archive.ubuntu.com/ubuntu', 'SECURITY': 'http://security.ubuntu.com/ubuntu', 'MIRROR': 'http://archive.ubuntu.com/ubuntu'}
2025-03-28 15:02:07,419 - handlers.py[DEBUG]: finish: modules-config/config-apt_configure: SUCCESS: config-apt_configure ran successfully and took 0.178 seconds
2025-03-28 15:02:07,419 - modules.py[DEBUG]: Running module timezone (<module 'cloudinit.config.cc_timezone' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_timezone.py'>) with frequency once-per-instance
2025-03-28 15:02:07,420 - handlers.py[DEBUG]: start: modules-config/config-timezone: running config-timezone with frequency once-per-instance
2025-03-28 15:02:07,421 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/iid-datasource-none/sem/config_timezone - wb: [644] 25 bytes
2025-03-28 15:02:07,424 - helpers.py[DEBUG]: Running config-timezone using lock (<FileLock using file '/var/lib/cloud/instances/iid-datasource-none/sem/config_timezone'>)
2025-03-28 15:02:07,444 - util.py[DEBUG]: Writing to /etc/timezone - wb: [644] 13 bytes
2025-03-28 15:02:07,446 - util.py[DEBUG]: Attempting to remove /etc/localtime
2025-03-28 15:02:07,448 - handlers.py[DEBUG]: finish: modules-config/config-timezone: SUCCESS: config-timezone ran successfully and took 0.028 seconds
2025-03-28 15:02:07,448 - modules.py[DEBUG]: Running module byobu (<module 'cloudinit.config.cc_byobu' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_byobu.py'>) with frequency once-per-instance
2025-03-28 15:02:07,449 - handlers.py[DEBUG]: start: modules-config/config-byobu: running config-byobu with frequency once-per-instance
2025-03-28 15:02:07,449 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/iid-datasource-none/sem/config_byobu - wb: [644] 25 bytes
2025-03-28 15:02:07,454 - helpers.py[DEBUG]: Running config-byobu using lock (<FileLock using file '/var/lib/cloud/instances/iid-datasource-none/sem/config_byobu'>)
2025-03-28 15:02:07,454 - cc_byobu.py[DEBUG]: Skipping module named byobu, no 'byobu' values found
2025-03-28 15:02:07,454 - handlers.py[DEBUG]: finish: modules-config/config-byobu: SUCCESS: config-byobu ran successfully and took 0.005 seconds
2025-03-28 15:02:07,454 - main.py[DEBUG]: Ran 6 modules with 0 failures
2025-03-28 15:02:07,455 - util.py[DEBUG]: Reading from /proc/uptime (quiet=False)
2025-03-28 15:02:07,455 - util.py[DEBUG]: Reading 12 bytes from /proc/uptime
2025-03-28 15:02:07,456 - atomic_helper.py[DEBUG]: Atomically writing to file /var/lib/cloud/data/status.json (via temporary file /var/lib/cloud/data/tmpvo7iu_6w) - w: [644] 499 bytes/chars
2025-03-28 15:02:07,459 - performance.py[DEBUG]: cloud-init stage: 'modules-config' took 8.630 seconds
2025-03-28 15:02:07,460 - handlers.py[DEBUG]: finish: modules-config: SUCCESS: running modules for config
2025-03-28 15:03:01,438 - log_util.py[DEBUG]: Cloud-init v. 24.4-0ubuntu1~24.04.2 running 'modules:final' at Fri, 28 Mar 2025 15:03:01 +0000. Up 141.99 seconds.
2025-03-28 15:03:01,439 - main.py[INFO]: PID [1] started cloud-init 'modules:final'.
2025-03-28 15:03:01,714 - stages.py[DEBUG]: Using distro class <class 'cloudinit.distros.ubuntu.Distro'>
2025-03-28 15:03:01,722 - modules.py[INFO]: Skipping modules 'package_update_upgrade_install,fan,landscape,lxd,ubuntu_drivers,puppet,chef,ansible,mcollective,salt_minion,phone_home,power_state_change' because no applicable config is provided.
2025-03-28 15:03:01,724 - modules.py[DEBUG]: Running module write_files_deferred (<module 'cloudinit.config.cc_write_files_deferred' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_write_files_deferred.py'>) with frequency once-per-instance
2025-03-28 15:03:01,725 - handlers.py[DEBUG]: start: modules-final/config-write_files_deferred: running config-write_files_deferred with frequency once-per-instance
2025-03-28 15:03:01,726 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/iid-datasource-none/sem/config_write_files_deferred - wb: [644] 25 bytes
2025-03-28 15:03:01,728 - helpers.py[DEBUG]: Running config-write_files_deferred using lock (<FileLock using file '/var/lib/cloud/instances/iid-datasource-none/sem/config_write_files_deferred'>)
2025-03-28 15:03:01,728 - util.py[DEBUG]: Writing to /etc/cloud/cloud-init.disabled - wb: [644] 132 bytes
2025-03-28 15:03:01,730 - util.py[DEBUG]: Changing the ownership of /etc/cloud/cloud-init.disabled to 0:0
2025-03-28 15:03:01,731 - handlers.py[DEBUG]: finish: modules-final/config-write_files_deferred: SUCCESS: config-write_files_deferred ran successfully and took 0.005 seconds
2025-03-28 15:03:01,731 - modules.py[DEBUG]: Running module reset_rmc (<module 'cloudinit.config.cc_reset_rmc' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_reset_rmc.py'>) with frequency once-per-instance
2025-03-28 15:03:01,731 - handlers.py[DEBUG]: start: modules-final/config-reset_rmc: running config-reset_rmc with frequency once-per-instance
2025-03-28 15:03:01,732 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/iid-datasource-none/sem/config_reset_rmc - wb: [644] 25 bytes
2025-03-28 15:03:01,733 - helpers.py[DEBUG]: Running config-reset_rmc using lock (<FileLock using file '/var/lib/cloud/instances/iid-datasource-none/sem/config_reset_rmc'>)
2025-03-28 15:03:01,734 - cc_reset_rmc.py[DEBUG]: Skipping creation of new ct_node_id node
2025-03-28 15:03:01,734 - handlers.py[DEBUG]: finish: modules-final/config-reset_rmc: SUCCESS: config-reset_rmc ran successfully and took 0.002 seconds
2025-03-28 15:03:01,734 - modules.py[DEBUG]: Running module scripts_vendor (<module 'cloudinit.config.cc_scripts_vendor' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_scripts_vendor.py'>) with frequency once-per-instance
2025-03-28 15:03:01,735 - handlers.py[DEBUG]: start: modules-final/config-scripts_vendor: running config-scripts_vendor with frequency once-per-instance
2025-03-28 15:03:01,736 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/iid-datasource-none/sem/config_scripts_vendor - wb: [644] 24 bytes
2025-03-28 15:03:01,737 - helpers.py[DEBUG]: Running config-scripts_vendor using lock (<FileLock using file '/var/lib/cloud/instances/iid-datasource-none/sem/config_scripts_vendor'>)
2025-03-28 15:03:01,738 - handlers.py[DEBUG]: finish: modules-final/config-scripts_vendor: SUCCESS: config-scripts_vendor ran successfully and took 0.002 seconds
2025-03-28 15:03:01,738 - modules.py[DEBUG]: Running module scripts_per_once (<module 'cloudinit.config.cc_scripts_per_once' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_scripts_per_once.py'>) with frequency once
2025-03-28 15:03:01,738 - handlers.py[DEBUG]: start: modules-final/config-scripts_per_once: running config-scripts_per_once with frequency once
2025-03-28 15:03:01,739 - util.py[DEBUG]: Writing to /var/lib/cloud/sem/config_scripts_per_once.once - wb: [644] 25 bytes
2025-03-28 15:03:01,740 - helpers.py[DEBUG]: Running config-scripts_per_once using lock (<FileLock using file '/var/lib/cloud/sem/config_scripts_per_once.once'>)
2025-03-28 15:03:01,741 - handlers.py[DEBUG]: finish: modules-final/config-scripts_per_once: SUCCESS: config-scripts_per_once ran successfully and took 0.002 seconds
2025-03-28 15:03:01,741 - modules.py[DEBUG]: Running module scripts_per_boot (<module 'cloudinit.config.cc_scripts_per_boot' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_scripts_per_boot.py'>) with frequency always
2025-03-28 15:03:01,742 - handlers.py[DEBUG]: start: modules-final/config-scripts_per_boot: running config-scripts_per_boot with frequency always
2025-03-28 15:03:01,743 - helpers.py[DEBUG]: Running config-scripts_per_boot using lock (<cloudinit.helpers.DummyLock object at 0x7e54e580dac0>)
2025-03-28 15:03:01,743 - handlers.py[DEBUG]: finish: modules-final/config-scripts_per_boot: SUCCESS: config-scripts_per_boot ran successfully and took 0.000 seconds
2025-03-28 15:03:01,743 - modules.py[DEBUG]: Running module scripts_per_instance (<module 'cloudinit.config.cc_scripts_per_instance' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_scripts_per_instance.py'>) with frequency once-per-instance
2025-03-28 15:03:01,744 - handlers.py[DEBUG]: start: modules-final/config-scripts_per_instance: running config-scripts_per_instance with frequency once-per-instance
2025-03-28 15:03:01,744 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/iid-datasource-none/sem/config_scripts_per_instance - wb: [644] 25 bytes
2025-03-28 15:03:01,746 - helpers.py[DEBUG]: Running config-scripts_per_instance using lock (<FileLock using file '/var/lib/cloud/instances/iid-datasource-none/sem/config_scripts_per_instance'>)
2025-03-28 15:03:01,746 - handlers.py[DEBUG]: finish: modules-final/config-scripts_per_instance: SUCCESS: config-scripts_per_instance ran successfully and took 0.002 seconds
2025-03-28 15:03:01,746 - modules.py[DEBUG]: Running module scripts_user (<module 'cloudinit.config.cc_scripts_user' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_scripts_user.py'>) with frequency once-per-instance
2025-03-28 15:03:01,747 - handlers.py[DEBUG]: start: modules-final/config-scripts_user: running config-scripts_user with frequency once-per-instance
2025-03-28 15:03:01,748 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/iid-datasource-none/sem/config_scripts_user - wb: [644] 25 bytes
2025-03-28 15:03:01,749 - helpers.py[DEBUG]: Running config-scripts_user using lock (<FileLock using file '/var/lib/cloud/instances/iid-datasource-none/sem/config_scripts_user'>)
2025-03-28 15:03:01,749 - handlers.py[DEBUG]: finish: modules-final/config-scripts_user: SUCCESS: config-scripts_user ran successfully and took 0.002 seconds
2025-03-28 15:03:01,750 - modules.py[DEBUG]: Running module ssh_authkey_fingerprints (<module 'cloudinit.config.cc_ssh_authkey_fingerprints' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_ssh_authkey_fingerprints.py'>) with frequency once-per-instance
2025-03-28 15:03:01,750 - handlers.py[DEBUG]: start: modules-final/config-ssh_authkey_fingerprints: running config-ssh_authkey_fingerprints with frequency once-per-instance
2025-03-28 15:03:01,751 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/iid-datasource-none/sem/config_ssh_authkey_fingerprints - wb: [644] 25 bytes
2025-03-28 15:03:01,752 - helpers.py[DEBUG]: Running config-ssh_authkey_fingerprints using lock (<FileLock using file '/var/lib/cloud/instances/iid-datasource-none/sem/config_ssh_authkey_fingerprints'>)
2025-03-28 15:03:01,754 - util.py[DEBUG]: Changing the ownership of /home/rajesh/.ssh to 1000:1000
2025-03-28 15:03:01,754 - util.py[DEBUG]: Writing to /home/rajesh/.ssh/authorized_keys - wb: [600] 0 bytes
2025-03-28 15:03:01,755 - util.py[DEBUG]: Changing the ownership of /home/rajesh/.ssh/authorized_keys to 1000:1000
2025-03-28 15:03:01,756 - util.py[DEBUG]: Reading from /home/rajesh/.ssh/authorized_keys (quiet=False)
2025-03-28 15:03:01,756 - util.py[DEBUG]: Reading 0 bytes from /home/rajesh/.ssh/authorized_keys
2025-03-28 15:03:01,757 - handlers.py[DEBUG]: finish: modules-final/config-ssh_authkey_fingerprints: SUCCESS: config-ssh_authkey_fingerprints ran successfully and took 0.006 seconds
2025-03-28 15:03:01,757 - modules.py[DEBUG]: Running module keys_to_console (<module 'cloudinit.config.cc_keys_to_console' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_keys_to_console.py'>) with frequency once-per-instance
2025-03-28 15:03:01,757 - handlers.py[DEBUG]: start: modules-final/config-keys_to_console: running config-keys_to_console with frequency once-per-instance
2025-03-28 15:03:01,758 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/iid-datasource-none/sem/config_keys_to_console - wb: [644] 25 bytes
2025-03-28 15:03:01,759 - helpers.py[DEBUG]: Running config-keys_to_console using lock (<FileLock using file '/var/lib/cloud/instances/iid-datasource-none/sem/config_keys_to_console'>)
2025-03-28 15:03:01,760 - subp.py[DEBUG]: Running command ['/usr/lib/cloud-init/write-ssh-key-fingerprints', '', ''] with allowed return codes [0] (shell=False, capture=True)
2025-03-28 15:03:01,932 - performance.py[DEBUG]: Running ['/usr/lib/cloud-init/write-ssh-key-fingerprints', '', ''] took 0.172 seconds
2025-03-28 15:03:01,934 - handlers.py[DEBUG]: finish: modules-final/config-keys_to_console: SUCCESS: config-keys_to_console ran successfully and took 0.176 seconds
2025-03-28 15:03:01,934 - modules.py[DEBUG]: Running module install_hotplug (<module 'cloudinit.config.cc_install_hotplug' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_install_hotplug.py'>) with frequency once-per-instance
2025-03-28 15:03:01,935 - handlers.py[DEBUG]: start: modules-final/config-install_hotplug: running config-install_hotplug with frequency once-per-instance
2025-03-28 15:03:01,936 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/iid-datasource-none/sem/config_install_hotplug - wb: [644] 25 bytes
2025-03-28 15:03:01,937 - helpers.py[DEBUG]: Running config-install_hotplug using lock (<FileLock using file '/var/lib/cloud/instances/iid-datasource-none/sem/config_install_hotplug'>)
2025-03-28 15:03:01,938 - util.py[DEBUG]: Reading from /var/lib/cloud/hotplug.enabled (quiet=False)
2025-03-28 15:03:01,938 - util.py[DEBUG]: File not found: /var/lib/cloud/hotplug.enabled
2025-03-28 15:03:01,939 - stages.py[DEBUG]: Allowed events: {<EventScope.NETWORK: 'network'>: {<EventType.BOOT_NEW_INSTANCE: 'boot-new-instance'>}}
2025-03-28 15:03:01,939 - stages.py[DEBUG]: Event Denied: scopes=['network'] EventType=hotplug
2025-03-28 15:03:01,939 - cc_install_hotplug.py[DEBUG]: Skipping hotplug install, not enabled
2025-03-28 15:03:01,939 - handlers.py[DEBUG]: finish: modules-final/config-install_hotplug: SUCCESS: config-install_hotplug ran successfully and took 0.004 seconds
2025-03-28 15:03:01,940 - modules.py[DEBUG]: Running module final_message (<module 'cloudinit.config.cc_final_message' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_final_message.py'>) with frequency always
2025-03-28 15:03:01,940 - handlers.py[DEBUG]: start: modules-final/config-final_message: running config-final_message with frequency always
2025-03-28 15:03:01,940 - helpers.py[DEBUG]: Running config-final_message using lock (<cloudinit.helpers.DummyLock object at 0x7e54e580d730>)
2025-03-28 15:03:01,941 - util.py[DEBUG]: Reading from /proc/uptime (quiet=False)
2025-03-28 15:03:01,941 - util.py[DEBUG]: Reading 13 bytes from /proc/uptime
2025-03-28 15:03:01,957 - performance.py[DEBUG]: Rendering jinja2 template took 0.016 seconds
2025-03-28 15:03:01,958 - log_util.py[DEBUG]: Cloud-init v. 24.4-0ubuntu1~24.04.2 finished at Fri, 28 Mar 2025 15:03:01 +0000. Datasource DataSourceNone.  Up 142.60 seconds
2025-03-28 15:03:01,958 - util.py[DEBUG]: Writing to /var/lib/cloud/instance/boot-finished - wb: [644] 68 bytes
2025-03-28 15:03:01,960 - handlers.py[DEBUG]: finish: modules-final/config-final_message: SUCCESS: config-final_message ran successfully and took 0.019 seconds
2025-03-28 15:03:01,961 - main.py[DEBUG]: Ran 11 modules with 0 failures
2025-03-28 15:03:01,961 - util.py[DEBUG]: Reading from /proc/uptime (quiet=False)
2025-03-28 15:03:01,962 - util.py[DEBUG]: Reading 13 bytes from /proc/uptime
2025-03-28 15:03:01,963 - atomic_helper.py[DEBUG]: Atomically writing to file /var/lib/cloud/data/status.json (via temporary file /var/lib/cloud/data/tmp96vggyrm) - w: [644] 503 bytes/chars
2025-03-28 15:03:01,965 - atomic_helper.py[DEBUG]: Atomically writing to file /var/lib/cloud/data/result.json (via temporary file /var/lib/cloud/data/tmp70iqko68) - w: [644] 65 bytes/chars
2025-03-28 15:03:01,966 - util.py[DEBUG]: Creating symbolic link from '/run/cloud-init/result.json' => '../../var/lib/cloud/data/result.json'
2025-03-28 15:03:01,966 - performance.py[DEBUG]: cloud-init stage: 'modules-final' took 0.688 seconds
2025-03-28 15:03:01,966 - handlers.py[DEBUG]: finish: modules-final: SUCCESS: running modules for final
